version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketplace_api
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/home/appuser
      - NOTIF_SERVICE_URL=http://notificaciones:5001/notificar
    depends_on:
      - notificaciones
    networks:
      - red-marketplace

  notificaciones:
    build:
      context: .
      dockerfile: Dockerfile.notif
    container_name: marketplace_notificaciones
    restart: unless-stopped
    expose:
      - "5001"
    networks:
      - red-marketplace

networks:
  red-marketplace:
    driver: bridge
